#!/bin/ksh --login

module load rocoto

rocotorun -w /whome/amb-verif/ensemble/xml/retro/metplus_precip_retro_english_ic_spp_sppt_feb2019.xml -d /whome/amb-verif/ensemble/xml/retro/db/metplus_precip_retro_english_ic_spp_sppt_feb2019.db
